version: '3'

services:

  web:
    build:
      context: .
      dockerfile: ./Dockerfile
    hostname: web
    container_name: web
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./html:/var/www/html
    environment:
      - SERVER_NAME=calorich.net
      - DOCUMENT_ROOT=/var/www/html
